<div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4">
    <div>
        @if($invoice->brand?->image)
            @php
                $brandImagePath = public_path('storage/' . $invoice->brand->image);
                $brandImageSrc = ($forPdf ?? false) && is_file($brandImagePath)
                    ? $brandImagePath
                    : asset('storage/' . $invoice->brand->image);
            @endphp
            <img src="{{ $brandImageSrc }}" alt="{{ $invoice->brand_name }}" style="max-height:60px; max-width:200px;" class="mb-2">
        @endif
        <h4 class="mb-0">{{ $invoice->brand_name ?? 'Invoice' }}</h4>
        @if($invoice->company_name)
            <div class="text-muted small">{{ $invoice->company_name }}</div>
        @endif
    </div>
    <div class="text-md-end">
        <h3 class="mb-1">INVOICE</h3>
        <div><strong>{{ $invoice->invoice_number }}</strong></div>
        <div class="text-muted">Date: {{ $invoice->issued_at->format('d M Y') }}</div>
        @if($invoice->isVoid())
            <span class="badge bg-secondary mt-2">VOID</span>
        @endif
    </div>
</div>

<div class="row mb-4">
    <div class="col-md-6">
        <h6 class="text-muted text-uppercase small mb-2">Bill To</h6>
        <div class="fw-semibold">{{ $invoice->client_name }}</div>
        @if($invoice->client_email)
            <div>{{ $invoice->client_email }}</div>
        @endif
        @if($invoice->client_phone)
            <div>{{ $invoice->client_phone }}</div>
        @endif
    </div>
    <div class="col-md-6 text-md-end">
        <h6 class="text-muted text-uppercase small mb-2">Sale Reference</h6>
        <div>Sale #{{ $invoice->sale_id }}</div>
        @if($invoice->agent_name)
            <div class="small text-muted">Agent: {{ $invoice->agent_name }}</div>
        @endif
        @if($invoice->team_name)
            <div class="small text-muted">Team: {{ $invoice->team_name }}</div>
        @endif
    </div>
</div>

<table class="table table-bordered mb-3">
    <thead class="table-light">
        <tr>
            <th>Description</th>
            <th class="text-end" style="width:140px">Amount</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <strong>{{ $invoice->title }}</strong>
                @if($invoice->notes)
                    <div class="text-muted small mt-1">{!! nl2br(e($invoice->notes)) !!}</div>
                @endif
            </td>
            <td class="text-end">${{ number_format($invoice->amount, 2) }}</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th class="text-end">Invoice Amount</th>
            <th class="text-end">${{ number_format($invoice->amount, 2) }} {{ $invoice->currency }}</th>
        </tr>
        <tr>
            <td class="text-end text-muted">Sale Total (at issue)</td>
            <td class="text-end text-muted">${{ number_format($invoice->sale_total, 2) }}</td>
        </tr>
        <tr>
            <td class="text-end text-muted">Received (at issue)</td>
            <td class="text-end text-muted">${{ number_format($invoice->sale_received, 2) }}</td>
        </tr>
        <tr>
            <td class="text-end">Balance Due (at issue)</td>
            <td class="text-end fw-bold">${{ number_format($invoice->sale_balance, 2) }}</td>
        </tr>
    </tfoot>
</table>

<p class="text-muted small mb-0">
    Generated by {{ $invoice->creator?->name ?? 'System' }}
    on {{ $invoice->created_at->format('d M Y, h:i A') }}.
</p>
