@extends('admin.layout')

@section('title', 'Invoice ' . $invoice->invoice_number)
@section('page-title', 'Invoice ' . $invoice->invoice_number)
@section('page-icon', 'receipt')

@section('content')
<div class="mb-3 d-print-none">
    <button type="button" class="btn btn-primary btn-sm" onclick="window.print()">
        <i class="bi bi-printer"></i> Print
    </button>
    <a href="{{ route('admin.sales.show', $invoice->sale_id) }}" class="btn btn-outline-secondary btn-sm">Back to Sale</a>
    <a href="{{ route('admin.invoices.index') }}" class="btn btn-outline-secondary btn-sm">All Invoices</a>
    @if($canVoid)
    <form action="{{ route('admin.invoices.void', $invoice) }}" method="POST" class="d-inline js-admin-delete-form" data-swal-title="Void this invoice?">
        @csrf
        <button type="submit" class="btn btn-outline-danger btn-sm">Void Invoice</button>
    </form>
    @endif
</div>

<div class="card invoice-print-card">
    <div class="card-body p-4">
        <div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4">
            <div>
                @if($invoice->brand?->image)
                    <img src="{{ asset('storage/' . $invoice->brand->image) }}" alt="{{ $invoice->brand_name }}" style="max-height:60px; max-width:200px;" class="mb-2">
                @endif
                <h4 class="mb-0">{{ $invoice->brand_name ?? 'Invoice' }}</h4>
                @if($invoice->company_name)
                    <div class="text-muted small">{{ $invoice->company_name }}</div>
                @endif
            </div>
            <div class="text-md-end">
                <h3 class="mb-1">INVOICE</h3>
                <div><strong>{{ $invoice->invoice_number }}</strong></div>
                <div class="text-muted">Date: {{ $invoice->issued_at->format('d M Y') }}</div>
                @if($invoice->isVoid())
                    <span class="badge bg-secondary mt-2">VOID</span>
                @endif
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-md-6">
                <h6 class="text-muted text-uppercase small mb-2">Bill To</h6>
                <div class="fw-semibold">{{ $invoice->client_name }}</div>
                @if($invoice->client_email)
                    <div>{{ $invoice->client_email }}</div>
                @endif
                @if($invoice->client_phone)
                    <div>{{ $invoice->client_phone }}</div>
                @endif
            </div>
            <div class="col-md-6 text-md-end">
                <h6 class="text-muted text-uppercase small mb-2">Sale Reference</h6>
                <div>Sale #{{ $invoice->sale_id }}</div>
                @if($invoice->agent_name)
                    <div class="small text-muted">Agent: {{ $invoice->agent_name }}</div>
                @endif
                @if($invoice->team_name)
                    <div class="small text-muted">Team: {{ $invoice->team_name }}</div>
                @endif
            </div>
        </div>

        <table class="table table-bordered mb-3">
            <thead class="table-light">
                <tr>
                    <th>Description</th>
                    <th class="text-end" style="width:140px">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <strong>{{ $invoice->title }}</strong>
                        @if($invoice->notes)
                            <div class="text-muted small mt-1">{!! nl2br(e($invoice->notes)) !!}</div>
                        @endif
                    </td>
                    <td class="text-end">${{ number_format($invoice->amount, 2) }}</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th class="text-end">Invoice Amount</th>
                    <th class="text-end">${{ number_format($invoice->amount, 2) }} {{ $invoice->currency }}</th>
                </tr>
                <tr>
                    <td class="text-end text-muted">Sale Total (at issue)</td>
                    <td class="text-end text-muted">${{ number_format($invoice->sale_total, 2) }}</td>
                </tr>
                <tr>
                    <td class="text-end text-muted">Received (at issue)</td>
                    <td class="text-end text-muted">${{ number_format($invoice->sale_received, 2) }}</td>
                </tr>
                <tr>
                    <td class="text-end">Balance Due (at issue)</td>
                    <td class="text-end fw-bold">${{ number_format($invoice->sale_balance, 2) }}</td>
                </tr>
            </tfoot>
        </table>

        <p class="text-muted small mb-0">
            Generated by {{ $invoice->creator?->name ?? 'System' }}
            on {{ $invoice->created_at->format('d M Y, h:i A') }}.
        </p>
    </div>
</div>
@endsection

@push('styles')
<style>
@media print {
    .sidebar, main > .page-header, .d-print-none, .alert, .toast-container, .live-notification-toast-wrap {
        display: none !important;
    }
    main {
        margin-left: 0 !important;
        padding: 0 !important;
    }
    .invoice-print-card {
        border: none !important;
        box-shadow: none !important;
    }
    .invoice-print-card .card-body {
        padding: 0 !important;
    }
}
</style>
@endpush
